export const skills = [
    'Gestion de projet (SCRUM)',
    'Responsive Design',
    'Git',
    'Git flow',
    'MongoDB',
    'MySQL',
    'Knex / Objection',
    'Mongoose',
    'Ant Design',
    'Material UI',
    'Bootstrap',
    'Firebase',
    'API Rest',
];